name: create-task

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      description:
        required: false
        type: string
      labels:
        required: false
        type: string
      priority:
        required: true
        type: number
      due_string:
        required: false
        type: string
      project_id:
        required: true
        type: number
    secrets:
      token:
        required: true

jobs:    
  create-task:
    runs-on: ubuntu-latest
    steps:
      - name: Where am I
        shell: pwsh
        run: |
          Get-ChildItem -recurse
        
      - name: Create task in Todoist
        shell: pwsh
        run: > 
          ./.github/pwsh/new-task.ps1 
            -title ${{ inputs.title }}
            -description ${{ inputs.description }}
            -labels ${{ inputs.labels }}
            -priority ${{ inputs.priority }}
            -due_string ${{ inputs.due_string }}
            -project_id ${{ inputs.project_id }}
            -token ${{ secrets.token }}
