name: reuse

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |       
          write-host "${{ inputs.message }}"
        shell: pwsh
        